services:
  postgre:
    image: postgres:12.17
    ports:
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: Pg123
      POSTGRES_USER: kubenews
      POSTGRES_DB: kubenews
    volumes:
      - postgre_docker_vol:/var/lib/postgresql/data
    networks:
      - kube_news_net
  
  kube_news:
    image: vianconi/kube-news:v2
    ports:
      - 8080:8080
    networks:
      - kube_news_net
    depends_on:
      - postgre
    environment:
      DB_PASSWORD: Pg123
      DB_USERNAME: kubenews
      DB_DATABASE: kubenews
      DB_HOST: postgre

volumes:
  postgre_docker_vol:

networks:
  kube_news_net:
    driver: bridge
      

